apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rc7o5e9u7-nodejs 
  janus-idp.io/tekton: rc7o5e9u7-nodejs
  backstage.io/kubernetes-id: rc7o5e9u7-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rc7o5e9u7-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml